package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import util.SettingHelper;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SettingsController implements Initializable{
	@FXML
	private Label labelIPBoardinfo;
	@FXML
	private TextField textFildIPBordInfo;
	@FXML
	private Button btnIPBoardInfo;
	@FXML
	private Label labelTeplate;
	@FXML
	private TextField textFildTeplate;
	@FXML
	private Button btnTeplate;
	@FXML
	private Label labelIZH;
	@FXML
	private TextField textFildZH;
	@FXML
	private Button btnZH;
	@FXML
	private Label labelEU;
	@FXML
	private TextField textFildEU;
	@FXML
	private Button btnEU;

	// Event Listener on Button[#btnIPBoardInfo].onAction
	@FXML
	public void btnIPBoardInfoClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnTeplate].onAction
	@FXML
	public void btnTeplateClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnZH].onAction
	@FXML
	public void btnZHClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEU].onAction
	@FXML
	public void btnEUClick(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		this.labelIPBoardinfo.setText("IPBoardInfo");
		this.labelTeplate.setText("Teplate    ");
		this.labelIZH.setText("ZH         ");
		this.labelEU.setText("EU         ");
		this.btnIPBoardInfo.setText("select");
		this.btnTeplate.setText("select");
		this.btnZH.setText("select");
		this.btnEU.setText("select");
		this.textFildIPBordInfo.setText(SettingHelper.IPBordInfo);
		this.textFildTeplate.setText(SettingHelper.Teplate);
		this.textFildZH.setText(SettingHelper.ZH);
		this.textFildEU.setText(SettingHelper.EU);
		
	}
}
